[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  port = 8888

# Simplify API redirects - try direct mapping first
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth/login"
  status = 200

[[redirects]]
  from = "/api/auth/logout"
  to = "/.netlify/functions/auth/logout"
  status = 200

[[redirects]]
  from = "/api/auth/verify"
  to = "/.netlify/functions/auth/verify"
  status = 200

[[redirects]]
  from = "/api/content"
  to = "/.netlify/functions/content"
  status = 200

[[redirects]]
  from = "/api/content/*"
  to = "/.netlify/functions/content/:splat"
  status = 200

# Admin routes
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin/dashboard"
  to = "/admin-dashboard.html"
  status = 200

[[redirects]]
  from = "/admin/projects"
  to = "/admin-projects.html"
  status = 200

# Legacy project routes (redirects)
[[redirects]]
  from = "/MyIsmail-Web/Projects"
  to = "/Projects/"
  status = 301

[[redirects]]
  from = "/MyIsmail-Web/Lessons/*"
  to = "/Lessons/:splat"
  status = 301

[[redirects]]
  from = "/MyIsmail-Web/Activities"
  to = "/Activities/"
  status = 301

[[redirects]]
  from = "/MyIsmail-Web/Soon/*"
  to = "/Soon/:splat"
  status = 301

# Function settings
[functions]
  node_bundler = "esbuild"